name: Deploy to Yegara Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Yegara via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cardanomining.com
          username: cardanas
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./build   # your local website folder
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/vendor/*
